### ISSUE TITLE
[Feat] NoSQL Backend

### ISSUE THREAD

**Issue by LuciAkirami** [tsterbak/promptmage#15]
It would be great if we could add support for a NoSQL Backend like MongoDB

**Comment by tsterbak** [comment]
Hm, what would be the usecase for this?
All the data is pretty structured and relational, so no need to add a NoSQL database from my point of view. Also, the DB should optimally not be touched by users of promptmage.

**Comment by LuciAkirami** [comment]
Yah, you are right. Closing this for now, will be opening when I find the right usecase for now
