### ISSUE TITLE
ValueError: No PromptMage instance found in the module.

### ISSUE THREAD

**Issue by LuciAkirami** [tsterbak/promptmage#3]
Getting Value Error for below code when I run `promptmage run test.py`
```python
from typing import List
from openai import OpenAI
from dotenv import load_dotenv

from promptmage import PromptMage, Prompt, MageResult

load_dotenv()


client = OpenAI()

# Create a new PromptMage instance
mage = PromptMage(
    name="simple-question-answer",
    available_models=["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-4", "gpt-3.5-turbo"],
)

@mage.step(
    name="question_answer_bot",
    prompt_name="qa_bot",
    initial=True,
)
def question_answer_bot(
    question: str, prompt: Prompt, model: str = "gpt-4o-mini"
) -> List[MageResult]:
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": prompt.system},
            {
                "role": "user",
                "content": prompt.user.format(question=question),
            },
        ],
    )
    output = response.choices[0].message.content
    return MageResult(result=output)
```

It's happening at line 62 in cli.py

Error
```
  File "/home/user/miniconda3/lib/python3.11/site-packages/promptmage/cli.py", line 62, in run
    raise ValueError("No PromptMage instance found in the module.")
ValueError: No PromptMage instance found in the module.
```

cli.py
```python
    # get the available flows from the source file
    available_flows = get_flows(file_path)

    if not available_flows:
        raise ValueError("No PromptMage instance found in the module.")
```

I copied the get_flows() command to a  a new .py file and gave the file_path as the path in which the above code contains and it did ran without any errors and I got this output

```
2024-08-21 10:24:14.271 | INFO     | promptmage.mage:__init__:39 - Initialized PromptMage with name: simple-question-answer
[PromptMage(name=simple-question-answer, steps=['question_answer_bot'])]
```

**Comment by LuciAkirami** [comment]
Got the issue. If if the change the name of my file from test.py to something else like qa_bot.py it works (I have chosen test.py initially cause I want to test it)

**Comment by tsterbak** [comment]
Thanks for your interest in the project! :)

That's a curious issue... :sweat_smile: 
So it only happens when the file is called `test.py` but otherwise everything works?

**Comment by LuciAkirami** [comment]
Yah. It only happens when the file containing the flow is named test.py 

If it's named something else, then it works

**Comment by LuciAkirami** [comment]
The issue seems to be from the `import_module() ` function. When we give call `import_module('test')` i.e. considering my file is named as `test.py,` then the import_module goes to this place 

`<module 'test' from '/home/username/miniconda3/lib/python3.11/test/__init__.py'>`

But when I call it, let's say `import_module('promt_test')`, i.e. considering my file is named `promp_test.py` in which I have imported the PromptMage

`<module 'test1' from '/home/username/Desktop/projects/promptmage_testing/promt_test.py'>`

In this case, it's correctly pointing to the path. But if file name is `test.py`, stored in the same path as above, it gives the first path pointing to miniconda3

**Comment by tsterbak** [comment]
Seems to be a funny edge case. Won't fix for now :)
